import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/page";
import Provivders from "../../redux/provider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Provivders>
          <div className="container">
            <div className="basis-5/6 h-screen">
              {children}
            </div>
            <div className="bg-cyan-950 basis-1/6 h-screen text-white">
              <Navbar />
            </div>
          </div>
        </Provivders>

      </body>
    </html>
  );
}
